// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WestCoastEducation.web.Data;

#nullable disable

namespace WestCoastEducation.web.Data.Migrations
{
    [DbContext(typeof(WestCoastEducationContext))]
    [Migration("20221227145011_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("WestCoastEducation.web.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CourseEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseNumer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CourseStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnrollmentLimit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParticipantList")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
